# jwt configuration
jwt:
  signing-key: 'liutaoliutaoliutao'
  expires-time: 604801
  buffer-time: 86401
# mysql connect configuration
mysql:
  path: '127.0.0.1'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'gin-server'
  username: 'root'
  password: 'LiuTao0.1'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""