version: "3.4"

x-image:
  &default-image
    redis:6.0.6
x-restart:
  &default-restart
    always
x-command:
  &default-command
    redis-server /etc/redis/redis.conf
x-netmode:
  &default-netmode
    host

services:
  redis1:
    image: *default-image
    restart: *default-restart
    container_name: redis6-m1
    command: *default-command
    volumes:
      - ./6378/data:/data
      - ./6378/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode

  redis2:
    image: *default-image
    restart: *default-restart
    container_name: redis6-m2
    command: *default-command
    volumes:
      - ./6379/data:/data
      - ./6379/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode

  redis3:
    image: *default-image
    restart: *default-restart
    container_name: redis6-m3
    command: *default-command
    volumes:
      - ./6380/data:/data
      - ./6380/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode

  redis4:
    image: *default-image
    restart: *default-restart
    container_name: redis6-s1
    command: *default-command
    volumes:
      - ./6381/data:/data
      - ./6381/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode

  redis5:
    image: *default-image
    restart: *default-restart
    container_name: redis6-s2
    command: *default-command
    volumes:
      - ./6382/data:/data
      - ./6382/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode

  redis6:
    image: *default-image
    restart: *default-restart
    container_name: redis6-s3
    command: *default-command
    volumes:
      - ./6383/data:/data
      - ./6383/redis/redis.conf:/etc/redis/redis.conf
    privileged: true
    network_mode: *default-netmode